-- =============================================================================
-- Digitalizador Bonfim Web v1.0 — Schema PostgreSQL 16 (canônico)
-- =============================================================================
-- Fonte da verdade do modelo de dados. É aplicado pela migration inicial do
-- Alembic (backend/migrations/versions/0001_initial_schema.py).
--
-- Convenções:
--   * snake_case; PKs BIGINT GENERATED BY DEFAULT AS IDENTITY
--     (o "BY DEFAULT" permite que o ETL insira IDs legados explícitos e depois
--      reinicie a sequência — ver etl/).
--   * flags 'S'/'N' do legado viram BOOLEAN; datas viram TIMESTAMPTZ.
--   * timestamps de auditoria created_at / updated_at (trigger set_updated_at).
--   * Mapeamento com o legado Firebird documentado em docs/02-MODELO-DE-DADOS.md.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. Extensões e utilitários
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid(), digest()
CREATE EXTENSION IF NOT EXISTS citext;     -- e-mail/login case-insensitive

-- Trigger genérico para manter updated_at
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
   NEW.updated_at := now();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 1. Tipos enumerados
-- -----------------------------------------------------------------------------
CREATE TYPE usuario_status     AS ENUM ('pendente', 'ativo', 'bloqueado', 'desligado');
CREATE TYPE codigo_tipo        AS ENUM ('cadastro', 'login_2fa', 'reset_senha', 'alterar_email');
CREATE TYPE arquivo_papel      AS ENUM ('full', 'thumbnail', 'backup', 'assinado', 'certificado');
CREATE TYPE assinatura_status  AS ENUM ('pendente', 'valida', 'invalida', 'revogada');
CREATE TYPE volume_papel       AS ENUM ('gravacao', 'backup', 'thumbnail', 'alta');
-- Modo de integração com o sistema comercial do cliente (pdv_bonfim):
-- direct_db = leitura direta do banco do cliente (hoje); api = via REST (futuro próximo).
CREATE TYPE integracao_modo    AS ENUM ('direct_db', 'api', 'desativado');

-- =============================================================================
-- 2. SEGURANÇA / ACESSO
-- =============================================================================

-- 2.1 Grupos de usuário (ex GRUPO_USUARIO) ------------------------------------
CREATE TABLE grupo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao    VARCHAR(40) NOT NULL,
    ativo        BOOLEAN NOT NULL DEFAULT true,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE grupo IS 'Grupos de usuário (RBAC). Legado: GRUPO_USUARIO.';

-- 2.2 Usuários (ex USUARIO) ---------------------------------------------------
CREATE TABLE usuario (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login             CITEXT NOT NULL UNIQUE,
    nome              VARCHAR(100),
    email             CITEXT NOT NULL UNIQUE,
    -- Autenticação (req. 1-3): NUNCA guardar senha em texto puro (legado usava FONE2!)
    senha_hash        TEXT,                                   -- Argon2id; NULL enquanto pendente/reset
    email_verificado  BOOLEAN NOT NULL DEFAULT false,
    status            usuario_status NOT NULL DEFAULT 'pendente',
    is_admin          BOOLEAN NOT NULL DEFAULT false,
    grupo_id          BIGINT NOT NULL REFERENCES grupo(id),
    -- Controle de acesso
    tentativas_login  INTEGER NOT NULL DEFAULT 0,
    acesso_cancelado  BOOLEAN NOT NULL DEFAULT false,
    bloqueado_ate     TIMESTAMPTZ,
    ultimo_login      TIMESTAMPTZ,
    -- Cadastro / RH
    endereco          VARCHAR(100),
    cidade            VARCHAR(40),
    fone_principal    VARCHAR(20),
    fone_secundario   VARCHAR(20),
    data_cadastro     DATE,
    data_desligamento DATE,
    motivo_desligamento VARCHAR(200),
    -- Produtividade (apuração de digitalização — legado VLR_JPG_*/VLR_DG_*)
    vlr_jpg_pasta     NUMERIC(12,4),
    vlr_jpg_unit      NUMERIC(12,4),
    vlr_dg_pasta      NUMERIC(12,4),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE  usuario IS 'Usuários do sistema. Legado: USUARIO (senha saiu de FONE2 para senha_hash).';
COMMENT ON COLUMN usuario.senha_hash IS 'Hash Argon2id. NULL = usuário pendente ou em reset obrigatório.';
COMMENT ON COLUMN usuario.status IS 'pendente=aguardando confirmação de e-mail; ativo; bloqueado; desligado.';

-- 2.3 Permissão grupo x tipo de documento (ex GRUPO_TIPODOC) ------------------
--     (tabela criada após tipo_documento; ver seção de FK adiada abaixo)

-- 2.4 Códigos de verificação / OTP (req. 2-3) ---------------------------------
CREATE TABLE codigo_verificacao (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    tipo          codigo_tipo NOT NULL,
    codigo_hash   TEXT NOT NULL,               -- guardamos só o hash do OTP/token
    expira_em     TIMESTAMPTZ NOT NULL,
    consumido_em  TIMESTAMPTZ,
    tentativas    INTEGER NOT NULL DEFAULT 0,
    ip_origem     INET,
    contexto      JSONB,                        -- dados do código (ex.: {novo_email} na troca de e-mail)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE codigo_verificacao IS 'OTPs/tokens: confirmação de cadastro, 2FA, reset de senha e troca de e-mail.';
CREATE INDEX ix_codigo_usuario_tipo ON codigo_verificacao (usuario_id, tipo) WHERE consumido_em IS NULL;

-- 2.5 Sessões / refresh tokens ------------------------------------------------
CREATE TABLE sessao (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    refresh_token_hash TEXT NOT NULL UNIQUE,
    expira_em          TIMESTAMPTZ NOT NULL,
    revogado_em        TIMESTAMPTZ,
    ip_origem          INET,
    user_agent         TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE sessao IS 'Refresh tokens ativos por usuário (JWT). Permite logout/revogação.';

-- 2.6 Trilha de auditoria (LGPD) ----------------------------------------------
CREATE TABLE log_auditoria (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT REFERENCES usuario(id),
    acao         VARCHAR(60) NOT NULL,          -- login, download, assinatura, refugo, ...
    entidade     VARCHAR(40),                   -- documento, registro, usuario, ...
    entidade_id  BIGINT,
    detalhe      JSONB,
    ip_origem    INET,
    user_agent   TEXT,
    ocorrido_em  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE log_auditoria IS 'Trilha imutável de ações (acesso, download, assinatura). Append-only.';
CREATE INDEX ix_log_entidade  ON log_auditoria (entidade, entidade_id);
CREATE INDEX ix_log_usuario   ON log_auditoria (usuario_id, ocorrido_em);

-- =============================================================================
-- 3. CATÁLOGOS / TABELAS DE APOIO
-- =============================================================================

-- 3.1 Tipo de documento (ex TIPO_DOC) -----------------------------------------
CREATE TABLE tipo_documento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao        VARCHAR(20) NOT NULL,
    descricao_detalhada VARCHAR(100),
    frente_verso     BOOLEAN NOT NULL DEFAULT false,   -- legado FRENTE_VERSO 'S'/'N'
    indicacao_frente VARCHAR(50),
    qtde_folhas      INTEGER NOT NULL DEFAULT 1,
    pagina_inicial   INTEGER,
    ativo            BOOLEAN NOT NULL DEFAULT true,     -- legado SITUACAO
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE tipo_documento IS 'Catálogo de tipos de documento. Legado: TIPO_DOC.';

-- 3.2 Config de páginas por tipo (ex TIPO_DOC_NITI) ---------------------------
CREATE TABLE tipo_documento_pagina (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_doc_id    BIGINT NOT NULL REFERENCES tipo_documento(id) ON DELETE CASCADE,
    frente         BOOLEAN,
    verso          BOOLEAN,
    pagina         INTEGER
);
COMMENT ON TABLE tipo_documento_pagina IS 'Layout de páginas do tipo de documento. Legado: TIPO_DOC_NITI.';

-- 3.3 Permissão grupo x tipo de documento (ex GRUPO_TIPODOC) ------------------
CREATE TABLE grupo_tipo_documento (
    grupo_id     BIGINT NOT NULL REFERENCES grupo(id) ON DELETE CASCADE,
    tipo_doc_id  BIGINT NOT NULL REFERENCES tipo_documento(id) ON DELETE CASCADE,
    PRIMARY KEY (grupo_id, tipo_doc_id)
);
COMMENT ON TABLE grupo_tipo_documento IS 'Tipos de documento visíveis por grupo. Legado: GRUPO_TIPODOC.';

-- 3.4 Índices de arquivamento (ex INDICE_ORIGINAL / INDICE_APOS_1999) ---------
CREATE TABLE indice_original (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao  VARCHAR(70) NOT NULL
);
CREATE TABLE indice_apos_1999 (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao  VARCHAR(70) NOT NULL
);

-- 3.5 Motivos de refugo (ex MOTIVO) -------------------------------------------
CREATE TABLE motivo (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao  VARCHAR(50) NOT NULL
);
COMMENT ON TABLE motivo IS 'Motivos de refugo de imagem. Legado: MOTIVO.';

-- 3.6 Características (ex CARAC) -----------------------------------------------
CREATE TABLE caracteristica (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(20) NOT NULL,
    ativo      BOOLEAN NOT NULL DEFAULT true
);

-- =============================================================================
-- 4. STORAGE (conceito de "local de guarda" — req. 7-8, sistema de arquivos POSIX)
-- =============================================================================

-- 4.1 Volumes de storage (ex HD) ----------------------------------------------
-- Cada volume é uma raiz de disco/mount no Linux. Substitui as letras P:, K: ...
CREATE TABLE volume_storage (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(50) NOT NULL,
    raiz_full     VARCHAR(255),      -- ex: /srv/digitalizador/full   (legado PASTA_GRAVACAO)
    raiz_thumb    VARCHAR(255),      -- ex: /srv/digitalizador/thumb  (legado PASTA_THUMBNAIL)
    raiz_backup   VARCHAR(255),      -- ex: /srv/backup/digitalizador (legado PASTA_BACKUP)
    raiz_alta     VARCHAR(255),      -- (legado PASTA_ALTA)
    serial_fisico VARCHAR(40),
    ativo         BOOLEAN NOT NULL DEFAULT true,
    data_ativo    DATE,
    data_inativo  DATE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE volume_storage IS 'Raízes de disco (mounts) para guarda. Legado: HD (letras de drive Windows).';

-- 4.2 Arquivo físico guardado (parte física do ex REGISTRO_IMAGE) -------------
-- Nome ofuscado (UUID) sem rastreabilidade; nome original vai cifrado no metadado.
CREATE TABLE arquivo (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    documento_id   BIGINT,                 -- FK adiada (documento é criado adiante)
    papel          arquivo_papel NOT NULL, -- full / thumbnail / backup / assinado / certificado
    volume_id      BIGINT REFERENCES volume_storage(id),
    object_key     VARCHAR(255) NOT NULL,  -- caminho relativo à raiz: aaaa/mm/aa/bb/<uuid>.<ext>
    nome_original  BYTEA,                  -- nome original CIFRADO (app-level); nunca no caminho
    extensao       VARCHAR(10),
    mime           VARCHAR(100),
    tamanho_bytes  BIGINT,
    checksum_sha256 CHAR(64),              -- integridade e deduplicação
    largura_px     INTEGER,
    altura_px      INTEGER,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     BIGINT REFERENCES usuario(id)
);
COMMENT ON TABLE  arquivo IS 'Arquivo físico no storage POSIX. Nome = UUID (ofuscação). Legado: caminhos IMAGE/THUMBNAIL/BACKUP.';
COMMENT ON COLUMN arquivo.object_key IS 'Caminho relativo à raiz do volume; particionado por ano/mês + sharding do UUID.';
COMMENT ON COLUMN arquivo.nome_original IS 'Nome original do arquivo, CIFRADO na aplicação. Não expor.';
CREATE INDEX ix_arquivo_documento ON arquivo (documento_id, papel);
CREATE INDEX ix_arquivo_checksum  ON arquivo (checksum_sha256);

-- =============================================================================
-- 5. DOMÍNIO — CONTRATOS E DOCUMENTOS
-- =============================================================================

-- 5.1 Registro / contrato (ex REGISTRO) ---------------------------------------
-- titular / contrato / sepultado são IDs do sistema comercial (pdv_bonfim) — mantidos como inteiros.
CREATE TABLE registro (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titular                     INTEGER,
    contrato                    INTEGER,
    sepultado                   INTEGER,
    indice_original_id          BIGINT REFERENCES indice_original(id),
    indice_apos_1999_id         BIGINT REFERENCES indice_apos_1999(id),
    emissao_contrato_original   DATE,
    ultimo_ano_pago             INTEGER,
    lote                        VARCHAR(10),
    locacao_arquivo             VARCHAR(15),
    situacao_emissao            VARCHAR(5),
    registro_bonfim             INTEGER,
    -- Controle de processo (quem/quando digitalizou, ajustou, conferiu)
    usu_processo_jpg_id         BIGINT REFERENCES usuario(id),
    usu_data_jpg_ini            DATE,
    usu_data_jpg_fim            DATE,
    usu_ult_alteracao_id        BIGINT REFERENCES usuario(id),
    usu_processo_ajuste_id      BIGINT REFERENCES usuario(id),
    usu_data_ajuste_ini         DATE,
    usu_data_ajuste_fim         DATE,
    ajuste_dados_cliente        INTEGER,
    data_dados_cliente          DATE,
    data_conf_ult_ano           DATE,
    usuario_conf_ult_ano_id     BIGINT REFERENCES usuario(id),
    data_conf_emissao           DATE,
    usuario_conf_emissao_id     BIGINT REFERENCES usuario(id),
    data_conf_emissao_contrato  DATE,
    usuario_conf_emissao_contrato_id BIGINT REFERENCES usuario(id),
    cadastro                    TIMESTAMPTZ DEFAULT now(),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE registro IS 'Contrato/jazigo. Legado: REGISTRO. titular/contrato/sepultado são IDs externos (pdv_bonfim).';
CREATE INDEX ix_registro_contrato  ON registro (contrato);
CREATE INDEX ix_registro_titular   ON registro (titular);
CREATE INDEX ix_registro_sepultado ON registro (sepultado);
CREATE INDEX ix_registro_lote      ON registro (lote);

-- 5.2 Documento digitalizado (parte lógica do ex REGISTRO_IMAGE) --------------
CREATE TABLE documento (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id           BIGINT NOT NULL REFERENCES registro(id),
    tipo_doc_id           BIGINT REFERENCES tipo_documento(id),
    face                  CHAR(1) CHECK (face IN ('F','V')),  -- Frente / Verso (legado FRENTE)
    nr_folha              INTEGER,
    total_folhas          INTEGER,
    guia                  INTEGER,
    nr_guia               VARCHAR(10),
    pasta                 VARCHAR(5),
    -- Situação / qualidade
    refugada              BOOLEAN NOT NULL DEFAULT false,
    em_uso                BOOLEAN NOT NULL DEFAULT true,       -- legado USO
    -- Auditoria de imagem (ex proc AUDITA_IMAGEM)
    auditada_em           TIMESTAMPTZ,
    auditada_por_id       BIGINT REFERENCES usuario(id),
    -- Conferência de sepultado
    aceitou_qtde_sepultado BOOLEAN,
    data_conf_sepultado   DATE,
    usuario_conf_sep_id   BIGINT REFERENCES usuario(id),
    id_sepultado          INTEGER,
    -- Autoria
    usuario_insert_id     BIGINT REFERENCES usuario(id),
    usuario_ult_alteracao_id BIGINT REFERENCES usuario(id),
    cadastro              TIMESTAMPTZ DEFAULT now(),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE documento IS 'Documento digitalizado ligado a um contrato. Metadado do legado REGISTRO_IMAGE (o arquivo físico vai em arquivo).';
CREATE INDEX ix_documento_registro ON documento (registro_id);
CREATE INDEX ix_documento_tipo     ON documento (tipo_doc_id);

-- FK adiada: arquivo.documento_id -> documento.id
ALTER TABLE arquivo
    ADD CONSTRAINT fk_arquivo_documento
    FOREIGN KEY (documento_id) REFERENCES documento(id) ON DELETE CASCADE;

-- 5.3 Rastro do legado por documento (para migração dos binários — fase 3b) ---
CREATE TABLE documento_legado (
    documento_id        BIGINT PRIMARY KEY REFERENCES documento(id) ON DELETE CASCADE,
    registro_image_id   INTEGER,           -- PK legada REGISTRO_IMAGE
    legacy_image_path   VARCHAR(255),      -- ex: P:\08142008\FULL\297 19257-144612.jpg
    legacy_thumb_path   VARCHAR(255),
    legacy_backup_path  VARCHAR(255),
    legacy_hd_image     INTEGER,
    legacy_hd_thumb     INTEGER,
    legacy_hd_backup    INTEGER,
    nome_arquivo        VARCHAR(50),        -- legado NOME_ARQUIVO
    nome_arq_temp       VARCHAR(50),        -- legado NOME_ARQ_TEMP (nome do scanner)
    maquina_origem      VARCHAR(20),
    volume_origem       VARCHAR(15),
    caminho_origem      VARCHAR(150),
    tam_arq_logico      DOUBLE PRECISION,
    migrado_em          TIMESTAMPTZ         -- preenchido quando os binários forem copiados
);
COMMENT ON TABLE documento_legado IS 'Caminhos/HDs legados por documento; usado pela migração dos binários (fase 3b).';

-- 5.4 Refugo (ex REGISTRO_REFUGO) ---------------------------------------------
CREATE TABLE refugo (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_id           BIGINT REFERENCES registro(id),
    documento_id          BIGINT REFERENCES documento(id),
    motivo_id             BIGINT REFERENCES motivo(id),
    data                  TIMESTAMPTZ DEFAULT now(),
    usuario_id            BIGINT REFERENCES usuario(id),
    comentario            VARCHAR(200),
    resolvido             BOOLEAN NOT NULL DEFAULT false,
    data_resolvido        TIMESTAMPTZ,
    usuario_resolvido_id  BIGINT REFERENCES usuario(id),
    comentario_resolvido  VARCHAR(200),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE refugo IS 'Refugos (rejeições) de imagem com motivo e resolução. Legado: REGISTRO_REFUGO.';
CREATE INDEX ix_refugo_registro ON refugo (registro_id);
CREATE INDEX ix_refugo_motivo   ON refugo (motivo_id);

-- =============================================================================
-- 6. ASSINATURA DIGITAL A1 (req. 4-6)
-- =============================================================================

-- 6.1 Certificado A1 do usuário -----------------------------------------------
CREATE TABLE usuario_certificado (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    nome_titular       VARCHAR(150),
    cpf_cnpj           VARCHAR(20),
    arquivo_id         BIGINT REFERENCES arquivo(id),  -- .pfx guardado com papel='certificado' (cifrado)
    senha_pfx_cifrada  BYTEA NOT NULL,                 -- senha do PKCS#12 cifrada na aplicação
    numero_serie       VARCHAR(80),
    emissor            VARCHAR(200),
    validade_inicio    TIMESTAMPTZ,
    validade_fim       TIMESTAMPTZ,
    ativo              BOOLEAN NOT NULL DEFAULT true,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE  usuario_certificado IS 'Certificado A1 (PKCS#12/.pfx) do usuário para assinatura. Arquivo e senha guardados cifrados.';
COMMENT ON COLUMN usuario_certificado.senha_pfx_cifrada IS 'Senha do .pfx cifrada (app-level). Nunca em texto puro.';
CREATE INDEX ix_certificado_usuario ON usuario_certificado (usuario_id) WHERE ativo;

-- 6.2 Assinatura aplicada a um documento --------------------------------------
CREATE TABLE assinatura (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id       BIGINT NOT NULL REFERENCES documento(id),
    usuario_id         BIGINT NOT NULL REFERENCES usuario(id),
    certificado_id     BIGINT REFERENCES usuario_certificado(id),
    ordem              INTEGER NOT NULL,             -- 1ª, 2ª... assinatura no mesmo documento
    assinado_em        TIMESTAMPTZ NOT NULL DEFAULT now(),
    hash_documento     CHAR(64),                     -- SHA-256 do PDF assinado (revisão)
    arquivo_assinado_id BIGINT REFERENCES arquivo(id), -- PDF resultante (papel='assinado')
    -- Carimbo no rodapé da última folha (req. 5)
    carimbo_pagina     INTEGER,
    carimbo_nova_folha BOOLEAN NOT NULL DEFAULT false, -- true = foi preciso acrescentar folha
    carimbo_posicao    JSONB,                          -- {x, y, largura, altura}
    -- Verificação
    status             assinatura_status NOT NULL DEFAULT 'valida',
    verificado_em      TIMESTAMPTZ,
    detalhe_cadeia     JSONB,                          -- emissor, OCSP/CRL, timestamp, etc.
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (documento_id, ordem)
);
COMMENT ON TABLE  assinatura IS 'Assinatura digital PAdES aplicada a um documento. Append-only; múltiplas por documento.';
COMMENT ON COLUMN assinatura.carimbo_nova_folha IS 'true quando não coube no rodapé e foi acrescentada nova última folha.';
CREATE INDEX ix_assinatura_documento ON assinatura (documento_id);
CREATE INDEX ix_assinatura_usuario   ON assinatura (usuario_id, assinado_em);

-- =============================================================================
-- 7. PARÂMETROS GLOBAIS
-- =============================================================================

-- 7.1 Parâmetro global (singleton) (ex PARAM) ---------------------------------
CREATE TABLE parametro (
    id                   BOOLEAN PRIMARY KEY DEFAULT true CHECK (id),  -- garante 1 única linha
    volume_gravacao_id   BIGINT REFERENCES volume_storage(id),
    volume_backup_id     BIGINT REFERENCES volume_storage(id),
    volume_thumbnail_id  BIGINT REFERENCES volume_storage(id),
    locacao_atual        VARCHAR(15),
    gravacao_datacenter  BOOLEAN NOT NULL DEFAULT false,
    backup_datacenter    BOOLEAN NOT NULL DEFAULT false,
    -- Integração com o sistema comercial do cliente (pdv_bonfim)
    integracao_modo      integracao_modo NOT NULL DEFAULT 'direct_db',
    -- Configurações extensíveis: necessidades do fluxo de ÓBITOS e demais parâmetros
    -- de comportamento vão aqui (decisão: registrar essas necessidades no PARAM).
    -- Segredos de conexão (DSN/URL/credenciais) NÃO ficam aqui — vão em env/secrets.
    config               JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE  parametro IS 'Parâmetros globais (linha única). Legado: PARAM. Também guarda modo de integração e config de óbitos.';
COMMENT ON COLUMN parametro.integracao_modo IS 'direct_db (hoje: lê banco do cliente) | api (futuro) | desativado.';
COMMENT ON COLUMN parametro.config IS 'JSONB extensível: necessidades do fluxo de óbitos e outros flags de comportamento.';

-- 7.2 Parâmetro por usuário (ex PARAM_USUARIO) --------------------------------
CREATE TABLE parametro_usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    ult_ler_pasta  VARCHAR(150),
    apaga_origem   BOOLEAN NOT NULL DEFAULT false
);
COMMENT ON TABLE parametro_usuario IS 'Preferências por usuário (herdado do fluxo de scanner). Legado: PARAM_USUARIO.';

-- =============================================================================
-- 8. VIEWS
-- =============================================================================

-- Contagem de assinaturas por documento (para o selo "X assinaturas" — req. 6)
CREATE VIEW vw_documento_assinaturas AS
SELECT d.id                         AS documento_id,
       d.registro_id,
       count(a.id)                  AS qtde_assinaturas,
       max(a.assinado_em)           AS ultima_assinatura
FROM documento d
LEFT JOIN assinatura a ON a.documento_id = d.id AND a.status <> 'revogada'
GROUP BY d.id, d.registro_id;
COMMENT ON VIEW vw_documento_assinaturas IS 'Qtde de assinaturas válidas por documento (selo "X assinaturas").';

-- =============================================================================
-- 9. TRIGGERS de updated_at
-- =============================================================================
CREATE TRIGGER trg_grupo_upd            BEFORE UPDATE ON grupo               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_usuario_upd          BEFORE UPDATE ON usuario             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_tipo_documento_upd   BEFORE UPDATE ON tipo_documento      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_volume_storage_upd   BEFORE UPDATE ON volume_storage      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_registro_upd         BEFORE UPDATE ON registro            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_documento_upd        BEFORE UPDATE ON documento           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_usuario_cert_upd     BEFORE UPDATE ON usuario_certificado FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_parametro_upd        BEFORE UPDATE ON parametro           FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- FIM DO SCHEMA
-- =============================================================================
